### ISSUE TITLE
License warning is not user-friendly in demo

### ISSUE THREAD

**Issue by vladshcherbin** [nib-edit/Nib#146]
Hey 👋 

After using a few buttons in demo, a nasty warning is shown:

![image](https://user-images.githubusercontent.com/6711845/83789692-c1397300-a69f-11ea-8027-350aea502abb.png)

It stays even if you change page or open another tab which is far from being user-friendly 😞

**Comment by jpuri** [comment]
Hey plz use this site: https://nibedit.com/

That was testing site of vercel that I put there temporarily.

**Comment by vladshcherbin** [comment]
@jpuri thanks 😉
