### ISSUE TITLE
Demo not working?

### ISSUE THREAD

**Issue by sivadass** [nib-edit/Nib#61]
Please find the attached screenshot, geting 'Applying a mismatched transaction' error!

<img width="1440" alt="Screenshot 2019-09-09 at 8 45 45 PM" src="https://user-images.githubusercontent.com/10391786/64543447-dcf72f00-d342-11e9-901d-8aa8037e922d.png">

**Comment by jpuri** [comment]
@sivadass : thx for reporting this, I just fixed.
