### ISSUE TITLE
Does framework support converting from HTML to wysiwyg content?

### ISSUE THREAD

**Issue by volkanongun** [nib-edit/Nib#62]
I'm a user of draft js and i can be able to convert html to draft.js content. So if HTML conversion supported i can ex-change my code with Nib. Nib seems is much cleaner and elegant. :)

**Comment by jpuri** [comment]
Hey @volkanongun , it is possible to convert HTML to prosemirror JSON, but important is that the HTML tags, properties that you are using is supported by the prosemirror schema of the editor. Details about schema here: https://prosemirror.net/examples/schema/

If you share details of HTML tags and attributes, I will be able to tell better.

**Comment by Draeggiar** [comment]
Same question here. I used React Draft Wysiwyg, but it still lacks mobile support, so i would like siwtch to Nib. Is it possible to feed its value from Html ? In the exaples there is only solution for reading html value. 
Sample html form Draft:
`<p><em>Testowy </em><strong>atrybut</strong></p><ul><li>z</li></ul><ol><li style="text-align:right;">Rzeczy</li><ul><li><del>dużą </del></li></ul><ol><li style="text-align:justify;"><span style="font-size: 30px;">zobaczymy</span></li><ul><li>ilością</li></ul><ol><li style="text-align:center;"><ins>czy</ins></li></ol></ol></ol><p><a href="http://www.google.pl" target="_blank">to</a>&nbsp;</p><p><span style="color: rgb(184,49,47);">wogóle</span></p><p><span style="font-family: Times New Roman;">działa</span></p><p></p><img src="https://foreverframe.net/wp-content/uploads/2017/01/diagram-1024x621.png" alt="undefined" style="float:none;height: auto;width: auto"/><img src="https://foreverframe.net/wp-content/uploads/2017/01/diagram-1024x621.png" alt="undefined" style="float:none;height: auto;width: auto"/><p></p>`

**Comment by jgoodall628** [comment]
Same question here. I am trying to create a controller input using Nib. But once i save the html to the database. I can no longer load that html into the editor when the user wants to edit.

**Comment by jpuri** [comment]
`nib-converter@2.2.0` can be used to do that on client side. Details here: http://www.nibedit.com/index.html#/Demo/ConvertFromHTMLDemo

@jgoodall628: For saving into DB I would suggest using JSON format and use html format for display only.
