### ISSUE TITLE
How to integrate with Formik?

### ISSUE THREAD

**Issue by dariusrosendahl** [nib-edit/Nib#69]
Hi,

I'm trying to integrate your great editor with Formik in React.

My code:

```
import React, { useState } from 'react';
import { Input, Textarea, ErrrorMessage } from '../forms/Input';
import { Formik, Form } from 'formik';
import { ButtonFullWidth } from '../forms/Button';
import { Spinner } from '../common/Icons';
import Editor from "nib-core";


interface IProps {
	value: string;
	cardContentAction?: any;
}

const ComplexityEdit: React.FC<IProps> = ({ value, cardContentAction }) => {
	const [data, setData] = useState({ analysing: null });

	let onSubmit = (values) => {
		cardContentAction(values['complexity'])
	};

	const initialValue = {
		complexity: value,
	};
	const MyEditor = () => <Editor />;

	return (
		<div>
			<Formik
				onSubmit={onSubmit}
				initialValues={initialValue}
				render={({ errors, status, touched, isSubmitting}) => (
					<Form>
						<Input name='complexity' component={MyEditor} />
						<ButtonFullWidth type='submit'>Opslaan {isSubmitting && <Spinner />}</ButtonFullWidth>
					</Form>
				)}
			/>
		</div>
	);
};

export default ComplexityEdit;
```

This is a functional component that gets it's data from value and sends it back via cardContentAction. It works fine with an input or textarea but I can't figure out how to use initialValues or send the data back when I press submit.

Input is just a simple styled-component Field from Formik

**Comment by jpuri** [comment]
Hey @dariusrosendahl : I am looking at this api for formik https://jaredpalmer.com/formik/docs/api/field#field-render-props. It supports using input in 3 ways:
1. <Field component>
2. <Field render>
3. <Field children>

First one requires object with these props: onChange, onBlur, name, and value. Editor does not support `value` I have not added controlled behaviour to editor to keep its performance good. `onBlur` also is not there atm, but I will add this.

I suggest that you go with option 2 or 3 and write code to your to bridge the gap between editor api and what formik expects.

I hope it helps.

**Comment by dariusrosendahl** [comment]
Thank for the reply! I'll try it out
