### ISSUE TITLE
How do I clear user-entered data after submission

### ISSUE THREAD

**Issue by xiaokinglong** [nib-edit/Nib#74]
I just use this.setstate to change the value of defaultValue without any effect
```
this.setState({
  defaultValue: {
    doc: {
	 type: 'doc',
	 content: []
	}
    }
 });
```

**Comment by jpuri** [comment]
Hey @xiaokinglong : I see its limitation atm as editor does not support controlled mode. A workaround would be re-initialize the react component

```
if (!value) <Editor /> // blank
else <Editor defaultValue={...} /> // not blank
```

**Comment by xiaokinglong** [comment]
> 嘿@xiaokinglong：我看到了atm的局限性，因为编辑器不支持受控模式。解决方法将是重新初始化 反应成分
> 
> ```
> if (!value) <Editor /> // blank
> else <Editor defaultValue={...} /> // not blank
> ```
> 
> ![](chrome-extension://mdcffelghikdiafnfodjlgllenhlnejl/icons/copy.png)
> 我会尽快解决。
