### ISSUE TITLE
Adding options make module crash "inline block link list image history"

### ISSUE THREAD

**Issue by split750** [nib-edit/Nib#76]
`<Editor
                                    config={{
                                        plugins: { 
                                            options: "inline block link list image history",
                                            image: {
                                                uploadCallback
                                            }
                                        },
                                        toolbar: {
                                            options: "top",
                                            top: {
                                                block: { grouped },
                                                options: "inline block link list image history" /* link */
                                            }
                                        }
                                    }}
                                    onChange={this.handleChange2}
                                    defaultValue={defaultValue}
                                    styleConfig={{
                                        editor: () => ({
                                            height: "400px"
                                        })
                                    }}
                                />`  

![image](https://user-images.githubusercontent.com/1798895/70073115-9428dc80-15f8-11ea-9b22-759c0f0165f5.png)

**Comment by split750** [comment]
Solved by not adding history in the plugin object, only adding it to the tool bar object.  
See config here: https://github.com/nib-edit/Nib/blob/master/packages/core/src/config/editor.js

**Comment by jpuri** [comment]
👍 history is implicitly always added to plugins.
I will anyways fix this issue.
