### ISSUE TITLE
Cannot get what the uploadCallback should export

### ISSUE THREAD

**Issue by split750** [nib-edit/Nib#77]
Trying to return the object `{src: downloadURL}` but nothing is stopping the loading

![image](https://user-images.githubusercontent.com/1798895/70077795-cb4fbb80-1601-11ea-956e-76729db078af.png)  

![image](https://user-images.githubusercontent.com/1798895/70077959-21246380-1602-11ea-8356-2a8f850806d6.png)

**Comment by jpuri** [comment]
The function is expected to return a promise, refer example here: https://github.com/nib-edit/Nib/blob/master/packages/docs/common/uploadCallback.js#L1
