### ISSUE TITLE
Convert from HTML always giving this error

### ISSUE THREAD

**Issue by BassWow** [nib-edit/Nib#79]
Hi,

When entering html outside of tags it errors out for some reason. Keeps saying something about a Za component?

I have a couple of screenshots attached.

https://codesandbox.io/s/elegant-surf-rzr8y?fontsize=14&hidenavigation=1&theme=dark

![Screen Shot 2019-12-05 at 10 33 17 am](https://user-images.githubusercontent.com/48664551/70190739-dbbf7d80-174a-11ea-813d-1a9c3fbfcded.jpg)
![Screen Shot 2019-12-05 at 10 32 53 am](https://user-images.githubusercontent.com/48664551/70190740-dbbf7d80-174a-11ea-969e-3d78875c7dde.jpg)

**Comment by jpuri** [comment]
Plz provide sample html, also note that the converter will support only the HTML which is supported by editor schema.
