### ISSUE TITLE
Please add support to class names

### ISSUE THREAD

**Issue by WillisShek** [nib-edit/Nib#80]
Having default classes and allowing us to config the class names will be great as it provides more customization towards styling.

**Comment by jpuri** [comment]
Editor supports theming, check example here: http://www.nibedit.com/index.html#/Demo/Themed.

Default [styles](https://github.com/nib-edit/Nib/blob/master/packages/core/src/config/styles.js) can also be overridden as done here: https://github.com/nib-edit/Nib/blob/master/packages/docs/demo/FullPage/index.jsx#L8

I do not plan to add support for class names.
