### ISSUE TITLE
Additional attributes get ignored

### ISSUE THREAD

**Issue by rwaldron** [nib-edit/Nib#81]
I wrote a visitor function to traverse the doc tree, to enable checking image nodes for "alt" attributes and then force users to provide a description, then add the attr to the list of attrs. Then I discovered that they get discarded, which appears to be caused by the "schema" in https://github.com/nib-edit/Nib/blob/master/packages/schema/src/nodes/image.js. I'd like to open a pull request to fix this, if you're interested.

**Comment by jpuri** [comment]
@rwaldron : Thanks for PR, I will very soon release the change.

**Comment by jpuri** [comment]
`nib-core@2.3.9` has the change.
