### ISSUE TITLE
"hardBreak" is producing broken html

### ISSUE THREAD

**Issue by rwaldron** [nib-edit/Nib#83]
I wrote a visitor that replaces these nodes: 

```
{ type: "paragraph" }
```

With: 

```
{ type: "hardBreak" }
```

(because I need to preserve newlines)

But this is what `convertToHTML` produces: `<brundefined></br>`

**Comment by jpuri** [comment]
I am looking into this.

**Comment by jpuri** [comment]
`nib-converter@2.2.8` has the fix.

**Comment by rwaldron** [comment]
Very cool! Thanks so much
