### ISSUE TITLE
Auto submit form while pressing anywhere on toolbar

### ISSUE THREAD

**Issue by dzpt** [nib-edit/Nib#84]
`"nib-core": "^2.3.9",`

It auto submit form after pressing on any button on toolbar

**Comment by jpuri** [comment]
Looking into this.

**Comment by aaveidt** [comment]
@jpuri https://codesandbox.io/s/admiring-wind-qswo0
2.3.9 , onSubmit is trigged if you press on any toolbar button

**Comment by jpuri** [comment]
@dzpt PR is merged and released. Thanks 😄
