### ISSUE TITLE
Number of line breaks is growing

### ISSUE THREAD

**Issue by rwaldron** [nib-edit/Nib#86]
Somehow this: 

```
<p ><br></p><p >
```

Turns into this: 

```
<p ><br ><br></br></p><p >
```

By doing something as simple as focusing away from the editor and back.

Rick

**Comment by jpuri** [comment]
I am not able to replicate this, can you plz share ur code / screenshot.

**Comment by rwaldron** [comment]
@jpuri thanks for the quick response, here's a repro: https://codesandbox.io/s/semantic-ui-example-19tod

**Comment by rwaldron** [comment]
@jpuri just wanted to follow up and see if there was anything further I could do here?

**Comment by jpuri** [comment]
Hey @rwaldron : sorry for delay, I looked at shared example and found that structure of HTML is wrong according to schema. `br` is nested in `h1`:

![Screenshot 2019-12-21 at 10 49 17 PM](https://user-images.githubusercontent.com/2182307/71311295-43acde00-2444-11ea-8d90-9b44a4896ad4.png)

This nesting looks wrong. Conversion from/to HTML works as per defined schema.

**Comment by rwaldron** [comment]
@jpuri thanks for taking a look, unfortunately I think I may have mis-communicated the issue in first report. My initial html doesn't have a `<br>` nested in a `<h1>`. This was my initial html (from the example I linked to): 

```
const initialValuePulledFromDatabase = "<br>hi!";
```

Hopefully this super reduced case better illustrates the problem I'm running into: https://codesandbox.io/s/nib-reduced-wdzbh. The code for the reduction is: 

```js
import { convertFromHTML, convertToHTML } from "nib-converter";

const initialValue = "<br>hi!";
const a = convertFromHTML(initialValue);
const b = convertToHTML(a.doc);

console.log(`Initial Value: "${initialValue}"`);
console.log(`Converted From HTML (1): ${JSON.stringify(a, null, 2)}`);
console.log(`Converted Back To HTML (1): "${b}"`);

const c = convertFromHTML(b);
const d = convertToHTML(c.doc);

console.log(`Converted From HTML (2): ${JSON.stringify(c, null, 2)}`);
console.log(`Converted Back To HTML (2): "${d}"`);
```

Which outputs: 

```
Initial Value: "<br>hi!" 
Converted From HTML (1): {
  "doc": {
    "type": "doc",
    "content": [
      {
        "type": "heading",
        "attrs": {
          "level": 1
        },
        "content": [
          {
            "type": "hardBreak"
          },
          {
            "type": "text",
            "text": "hi!"
          }
        ]
      }
    ]
  },
  "selection": {
    "type": "text",
    "anchor": 0,
    "head": 0
  }
} 
Converted Back To HTML (1): "<h1 ><br ><br></br>hi!</h1>" 
Converted From HTML (2): {
  "doc": {
    "type": "doc",
    "content": [
      {
        "type": "heading",
        "attrs": {
          "level": 1
        },
        "content": [
          {
            "type": "hardBreak"
          },
          {
            "type": "hardBreak"
          },
          {
            "type": "hardBreak"
          },
          {
            "type": "text",
            "text": "hi!"
          }
        ]
      }
    ]
  },
  "selection": {
    "type": "text",
    "anchor": 0,
    "head": 0
  }
} 
Converted Back To HTML (2): "<h1 ><br ><br></br><br ><br></br><br ><br></br>hi!</h1>" 
```


The initial html string `"<br>hi!"` ends up being `"<h1 ><br ><br></br><br ><br></br><br ><br></br>hi!</h1>" ` after being converted from HTML and back to HTML twice
