### ISSUE TITLE
Heading dropdown not alligned correctly for chrome and firefox.

### ISSUE THREAD

**Issue by Puspendert** [nib-edit/Nib#87]
![Screenshot 2019-12-24 at 8 30 14 PM](https://user-images.githubusercontent.com/16055344/71417692-a5f81f80-268c-11ea-8c59-cc4d93a1ed96.png)
Chrome: 79.0.3945.88
FireFox: 71.0

**Comment by jpuri** [comment]
Again this is not replicating at my end. May be some css issue on ur page.

**Comment by jpuri** [comment]
![Screenshot 2020-01-03 at 11 22 23 AM](https://user-images.githubusercontent.com/2182307/71709087-5c8d9a00-2e1b-11ea-8935-7b75536b58d2.png)
