### ISSUE TITLE
FireFox: mouse/touchbar click not working for unselecting the text

### ISSUE THREAD

**Issue by Puspendert** [nib-edit/Nib#88]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/16055344/71424780-8f1cf180-26bb-11ea-8eed-a04f142aaf3f.gif)
If some text is selected and then mouse is clicked next to the selected text, it won't work. We need to click somewhere on other line to unselect the text.

MacOS 10.14.6
Firefox: 71.0

**Comment by jpuri** [comment]
Hello @Puspendert : I am not able to replicate this, can you share codepen or ur project on github.

**Comment by jpuri** [comment]
I am looking into this.

**Comment by jpuri** [comment]
`nib-core@2.5.1` has the fix.
