### ISSUE TITLE
Missing CSS

### ISSUE THREAD

**Issue by Hereward** [nib-edit/Nib#92]
In my implementation there is missing CSS, resulting in icons all being block elements, stacked vertically.

Missing CSS classes start with "rdw-".

![image](https://user-images.githubusercontent.com/1784096/72595575-b6728180-393c-11ea-8787-2eba25ad70a0.png)

**Comment by jpuri** [comment]
Hey @Hereward : these classes do not belong to nib. Nib uses `emotion` lib for styling and classes do not have this name.
May be some wrong classes are getting applied to the editor in this case, which are causing issue with display.

**Comment by Hereward** [comment]
Issue resolved - I was importing the react-draft-wysiwyg component by mistake.
