### ISSUE TITLE
Typed code (TypeScript, Flow...)

### ISSUE THREAD

**Issue by aried3r** [nib-edit/Nib#97]
Hey! I know this one is a lot to ask and I'd help out if we do end up using nib at work (and so far, it's our most favorite ProseMirror based editor! Thanks again for this project!).

We use TypeScript and while ProseMirror has types (can search for them [here](https://microsoft.github.io/TypeSearch/)), nib doesn't. I tried adding our own type definitions, but I could only get so far, because of some API decisions.

One thing I found harder to type strictly was passing options to the `Editor`. Instead of a list of strings (which would be easier to add types for, since you can also limit which strings are allowed) one has to pass one long string, which in the end is being `.split()`.

https://github.com/nib-edit/Nib/blob/8cc08f1b9e41c8bec5b6e170f9fc05ec60dee4f1/packages/core/src/config/editor.js#L22-L24

https://github.com/nib-edit/Nib/blob/8cc08f1b9e41c8bec5b6e170f9fc05ec60dee4f1/packages/core/src/utils/editor/toolbar.js#L4-L5

Example of how you can limit values in TypeScript in [dayjs](https://github.com/iamkun/dayjs/blob/144c2ae6e15fbf89e3acd7c8cb9e237c5f6e1348/types/index.d.ts#L11-L12):

```TypeScript
type UnitTypeShort = 'd' | 'M' | 'y' | 'h' | 'm' | 's' | 'ms'
export type UnitType = 'millisecond' | 'second' | 'minute' | 'hour' | 'day' | 'month' | 'year' | 'date' | UnitTypeShort;
```

If you're open to the idea, there's of course a few options. Either slowly add types, keeping them separate (like dayjs) does, or slowly convert the code base to TypeScript, thus not having to worry if the types are our of sync with the JavaScript code (of course there's tooling for that as well).

WDYT in general about this idea? Without having to commit to anything :)

**Comment by jpuri** [comment]
I want to slowly convert codebase to typescript. Sometime soon I will start converting codebase to TS and I will try to convert the interfaces sooner so users are good.

**Comment by aried3r** [comment]
Awesome, that's very good to hear! Whenever your start and if we decide to go with nib, we'll try to contribute.

**Comment by buixuanhai** [comment]
Could I contribute to convert to TS?, please a guide if possible.

**Comment by jpuri** [comment]
nib-core is code is already migrated to typescript. I will publish type declaration file soon.

**Comment by jpuri** [comment]
`nib-core@2.6.3` has declaration file added.
