### ISSUE TITLE
Editor has double scrollbar on edge

### ISSUE THREAD

**Issue by buixuanhai** [nib-edit/Nib#98]
![d766347a-ce5a-4070-9cdd-2608579034cc](https://user-images.githubusercontent.com/9126944/74214914-d85beb80-4cd1-11ea-836e-076abcc4eac2.png)
When using editor on Edge, it always shows a scrollbar, and when the editor has more content, it shows up another scrollbar.

**Comment by jpuri** [comment]
Released in `nib-core@2.6.1`
